"""Rename address column

Revision ID: 800ff0ff92aa
Revises: e72fcd3adc98
Create Date: 2024-10-04 03:57:30.632102

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '800ff0ff92aa'
down_revision = 'e72fcd3adc98'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('departments','address',new_column_name='location')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('departments','location',new_column_name='address')
    # ### end Alembic commands ###
