"""Rename department

Revision ID: e72fcd3adc98
Revises: 6d1b289934f0
Create Date: 2024-10-04 03:43:37.869284

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e72fcd3adc98'
down_revision = '6d1b289934f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
   op.rename_table('department','departments')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('departments','department')
    # ### end Alembic commands ###
